import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('Admin navigation, audit filters and encrypted CRUD work on desktop and mobile', async ({ page }) => {
  test.setTimeout(60000);
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('WebAuthn.enable');
  await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'usb', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const sent = []; page.on('request', request => { if (request.url().endsWith('/execute')) sent.push(request.postData()); });
  await page.setViewportSize({ width: 1440, height: 1000 });
  // An unauthenticated deep link must survive signing in.
  await page.goto('/admin/logs');
  await page.screenshot({ path: 'test-results/admin-login.png' });
  await page.getByLabel('Password', { exact: true }).fill('acceptance-test-password-only');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.locator('#workspace')).toBeVisible();
  await expect(page.locator('#value-dialog')).toBeVisible();
  await expect(page.locator('#value-text')).toHaveValue(/dvrc_/);
  await expect(page.locator('#value-type-label')).toBeHidden();
  await expect(page.locator('#save-value')).toBeHidden();
  await expect(page.locator('#value-text')).toHaveAttribute('readonly', '');
  await page.locator('#close-value').click();
  await expect(page.locator('#value-text')).toHaveValue('');
  await expect(page.locator('#audit-list tr').first()).toBeVisible();
  await expect(page).toHaveURL(/\/admin\/logs$/);
  const nav = page.getByRole('navigation', { name: 'Main navigation' });
  await nav.getByRole('link', { name: 'Buckets', exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/buckets$/);
  const name = 'payments_production';
  for (const [bucket, description] of [[name, 'Production credentials for the payments platform.'], ['payments_staging', 'Isolated secrets for integration tests and previews.'], ['payments_workers', 'Background jobs, queues, and scheduled processing.']]) {
    await page.getByRole('button', { name: 'New bucket', exact: true }).click();
    await page.locator('#bucket-form').getByLabel('Name', { exact: true }).fill(bucket);
    await page.locator('#bucket-form').getByLabel('Description', { exact: true }).fill(description);
    await page.getByRole('button', { name: 'Create bucket', exact: true }).click();
    await expect(page.getByRole('link', { name: 'Open ' + bucket, exact: true })).toBeVisible();
  }
  await page.getByLabel('Find a bucket', { exact: true }).fill('payments');
  await expect(page.locator('#bucket-list .card')).toHaveCount(3);
  await page.screenshot({ path: 'test-results/admin-buckets.png' });
  await page.getByRole('link', { name: 'Open ' + name, exact: true }).click();
  await expect(page).toHaveURL('/admin/buckets/' + name);
  await expect(page.locator('#bucket-title')).toHaveText(name);
  await page.reload();
  await expect(page.locator('#bucket-title')).toHaveText(name);
  const keyBox = await page.getByLabel('Key', { exact: true }).boundingBox();
  const valueBox = await page.locator('#secret-form textarea').boundingBox();
  expect(Math.abs(keyBox.y - valueBox.y)).toBeLessThan(2);
  expect(Math.abs(keyBox.height - valueBox.height)).toBeLessThan(2);
  await page.getByLabel('Key', { exact: true }).fill('ConnectionStrings:Main');
  await page.locator('#secret-form').getByLabel('Value', { exact: true }).fill('browser-secret-秘密');
  await page.getByRole('button', { name: 'Add secret', exact: true }).click();
  await page.getByRole('button', { name: 'Show / edit', exact: true }).click();
  await expect(page.locator('#value-text')).toHaveValue('browser-secret-秘密');
  await expect(page.getByLabel('Value type', { exact: true })).toBeVisible();
  await page.locator('#value-text').fill('updated');
  await page.getByRole('button', { name: 'Save change', exact: true }).click();
  await page.getByRole('button', { name: 'Show / edit', exact: true }).click();
  await expect(page.locator('#value-text')).toHaveValue('updated');
  // Browser history navigation also clears decrypted values and closes the dialog.
  await page.goBack();
  await expect(page).toHaveURL(/\/admin\/buckets$/);
  await expect(page.locator('#value-dialog')).not.toBeVisible();
  await expect(page.locator('#value-text')).toHaveValue('');
  await page.goForward();
  await expect(page).toHaveURL('/admin/buckets/' + name);
  await expect(page.getByRole('button', { name: 'Show / edit', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-secrets.png' });

  for (const [key, type, value] of [['Redis:Port', 'number', '6379'], ['Redis:Enabled', 'boolean', 'false'], ['Redis:Optional', 'null', ''], ['Literal\\:Name', 'string', '00123']]) {
    await page.getByLabel('Key', { exact: true }).fill(key);
    await page.getByLabel('Secret type', { exact: true }).selectOption(type);
    await page.locator('#secret-form').getByLabel('Value', { exact: true }).fill(value);
    await page.getByRole('button', { name: 'Add secret', exact: true }).click();
    await expect(page.locator('#secret-list')).toContainText(key);
  }
  const flagRow = page.locator('#secret-list article').filter({ hasText: 'Redis:Enabled' });
  await flagRow.getByRole('button', { name: 'Show / edit', exact: true }).click();
  await expect(page.getByLabel('Value type', { exact: true })).toHaveValue('boolean');
  await page.locator('#value-text').fill('true');
  await page.getByRole('button', { name: 'Save change', exact: true }).click();
  await page.getByRole('link', { name: 'Configuration', exact: true }).click();
  await expect(page).toHaveURL(/\?view=configuration$/);
  await expect(page.locator('#config-output')).toContainText('<hidden:number>');
  await expect(page.getByRole('button', { name: 'Copy configuration', exact: true })).toBeDisabled();
  await expect(page.locator('#config-output')).not.toContainText('updated');
  await page.getByRole('button', { name: 'Reveal all values', exact: true }).click();
  await expect(page.locator('#config-help')).toContainText('Values revealed');
  const config = JSON.parse(await page.locator('#config-output').textContent());
  expect(config.Redis).toEqual({ Port: 6379, Enabled: true, Optional: null });
  expect(config['Literal:Name']).toBe('00123');
  expect(config.ConnectionStrings.Main).toBe('updated');
  await page.screenshot({ path: 'test-results/admin-configuration.png' });
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download', exact: true }).click();
  const download = await downloadEvent;
  expect(JSON.parse(await readFile(await download.path(), 'utf8'))).toEqual(config);
  await page.getByLabel('Configuration format', { exact: true }).selectOption('yaml');
  await expect(page.locator('#config-output')).toContainText('"Port": 6379');
  await expect(page.locator('#config-output')).toContainText('"Enabled": true');
  await expect(page.locator('#config-output')).toContainText('"Literal:Name": "00123"');
  await page.getByRole('button', { name: 'Hide values', exact: true }).click();
  await expect(page.locator('#config-output')).not.toContainText('updated');
  await expect(page.getByRole('button', { name: 'Download', exact: true })).toBeDisabled();
  await page.reload();
  await expect(page.locator('#config-output')).toContainText('<hidden:');

  await nav.getByRole('link', { name: 'Access tokens', exact: true }).click();
  await expect(page.locator('#config-output')).toBeEmpty();
  await expect(page).toHaveURL(/\/admin\/tokens$/);
  await page.getByRole('button', { name: 'New token', exact: true }).click();
  await page.locator('#token-form').getByLabel('Name', { exact: true }).fill('Payments service');
  await page.getByRole('button', { name: 'Select bucket reader scopes' }).click();
  await page.locator('#token-buckets').getByLabel(name, { exact: true }).check();
  await page.getByRole('button', { name: 'Create token', exact: true }).click();
  await expect(page.locator('#value-text')).toHaveValue(/^dv1_[A-Za-z0-9_-]{60}$/);
  await expect(page.locator('#value-type-label')).toBeHidden();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(page.locator('#value-text')).toHaveValue('');
  const tokenRow = page.locator('#token-list article').filter({ hasText: 'Payments service' });
  page.once('dialog', dialog => dialog.accept()); await tokenRow.getByRole('button', { name: 'Revoke', exact: true }).click();
  await expect(tokenRow).toContainText('Revoked');
  await page.screenshot({ path: 'test-results/admin-tokens.png' });

  await nav.getByRole('link', { name: 'Activity logs', exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/logs$/);
  await expect(nav.getByRole('link', { name: 'Activity logs', exact: true })).toHaveAttribute('aria-current', 'page');
  const eventType = page.getByLabel('Event type', { exact: true });
  await expect(eventType).toHaveCSS('appearance', 'base-select');
  await eventType.click();
  await page.screenshot({ path: 'test-results/admin-select.png' });
  await page.getByRole('option', { name: 'Operations', exact: true }).click();
  await expect(eventType).toHaveValue('operation');
  await eventType.focus();
  await page.keyboard.press('Space');
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await expect(eventType).toHaveValue('http');
  await page.getByLabel('Search logs', { exact: true }).fill(name);
  await page.getByLabel('Event type', { exact: true }).selectOption('operation');
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/logs\?search=payments_production&kind=operation$/);
  await expect(page.locator('#audit-list')).toContainText('secret.update');
  await expect(page.locator('#audit-list')).not.toContainText('browser-secret-秘密');
  await page.reload();
  await expect(page.getByLabel('Search logs', { exact: true })).toHaveValue(name);
  await expect(page.getByLabel('Event type', { exact: true })).toHaveValue('operation');
  await expect(page.locator('#audit-list')).toContainText('secret.update');
  await page.locator('#audit-list button').first().click();
  await expect(page.locator('.log-details').first()).toBeVisible();
  await expect(page.locator('.log-details').first()).toContainText('Trace ID');
  await page.locator('#audit-list button').first().click();
  await page.screenshot({ path: 'test-results/admin-logs.png' });
  await page.getByLabel('Search logs', { exact: true }).fill('no-event-matches-this-string');
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.locator('#audit-empty')).toBeVisible();
  await page.goBack();
  await expect(page.locator('#audit-list')).toContainText('secret.update');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Apply filters', exact: true })).toBeVisible();
  await expect(nav.getByRole('link', { name: 'Settings', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/admin-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });

  await nav.getByRole('link', { name: 'Settings', exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/settings$/);
  const settingsHeading = await page.getByRole('heading', { name: 'Security settings', exact: true }).boundingBox();
  const passkeysHeading = await page.getByRole('heading', { name: 'Passkeys', exact: true }).boundingBox();
  expect(passkeysHeading.y).toBeGreaterThan(settingsHeading.y + settingsHeading.height);
  await page.screenshot({ path: 'test-results/admin-settings.png' });
  await page.getByLabel('Current password', { exact: true }).fill('acceptance-test-password-only');
  await page.getByLabel('New password', { exact: true }).fill('acceptance-test-password-updated');
  await page.getByRole('button', { name: 'Change password and sign out', exact: true }).click();
  await expect(page.locator('#login')).toBeVisible();
  await page.getByLabel('Password', { exact: true }).fill('acceptance-test-password-updated');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.locator('#password-view')).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.locator('#login')).toBeVisible();
  expect(errors).toEqual([]);
  expect(sent.length).toBeGreaterThan(0);
  expect(sent.every(body => body && !body.includes('browser-secret') && !body.includes('updated') && body.split('.').length === 5)).toBe(true);
});
